# Generated by Django 4.0 on 2022-01-08 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('parentsNames', models.TextField()),
                ('generationTag', models.IntegerField()),
                ('is_died', models.BooleanField(default=False)),
                ('color', models.CharField(max_length=7)),
                ('family', models.CharField(max_length=1)),
                ('father', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='father_children', to='decos.deco')),
                ('mother', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mother_children', to='decos.deco')),
            ],
        ),
        migrations.CreateModel(
            name='DNA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.TimeField(auto_now=True)),
                ('health', models.FloatField()),
                ('size', models.FloatField()),
                ('gender', models.IntegerField()),
                ('perception', models.FloatField()),
                ('maxSpeed', models.FloatField()),
                ('reportedAtGeneration', models.IntegerField()),
                ('createdAt', models.FloatField()),
                ('deco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='decos.deco')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
