# Generated by Django 4.0 on 2022-01-08 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Population',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_at', models.DateTimeField(auto_now=True)),
                ('population', models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='dna',
            options={'ordering': ('createdAt',)},
        ),
    ]
